version: "3.9"
   
services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
    # backend:
    #     build: ./backend
    #     command: ./backend/manage.py runserver 0.0.0.0:8000
    #     volumes:
    #     - .:/code
    #     ports:
    #     - "8000:8000"
        # depends_on:
        #   - db
        # ********************** run the front-end ***************
    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/code
            - /code/node_modules
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        # depends_on:
        #     - backend
        command: npm start