# Generated by Django 3.0.8 on 2021-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('issue', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
