# Generated by Django 3.0.8 on 2021-07-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='landingPAGE',
            new_name='LandingPageModel',
        ),
    ]
