# Generated by Django 3.0.8 on 2021-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_contact_us_issue_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='issue_resolved',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
