# Generated by Django 3.0.8 on 2021-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20210430_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='issue_resolved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
