# Generated by Django 3.0.8 on 2021-07-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_landingpagecrud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='landingPAGECRUD',
            new_name='landingPAGE',
        ),
    ]
