# Generated by Django 3.0.8 on 2021-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20210704_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='heading1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='heading2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='heading4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
